# Generated by Django 5.1.6 on 2025-02-23 03:51

from django.db import migrations


def transfer_prices(apps, schema_editor):
    TrainRoute = apps.get_model('myApp', 'TrainRoute')
    Ticket = apps.get_model('myApp', 'Ticket')
    
    for route in TrainRoute.objects.all():
        # Update all tickets for this route
        route_tickets = Ticket.objects.filter(route=route)
        for ticket in route_tickets:
            # Set price based on ticket type
            if ticket.ticket_type == 'day':
                ticket.price = float(route.price)
            elif ticket.ticket_type == 'week':
                ticket.price = float(route.price) * 5  # Weekly price (5x daily price)
            elif ticket.ticket_type == 'month':
                ticket.price = float(route.price) * 20  # Monthly price (20x daily price)
            ticket.save()

def reverse_transfer(apps, schema_editor):
    # If needed, we can reverse this migration
    Ticket = apps.get_model('myApp', 'Ticket')
    Ticket.objects.all().update(price=0)

class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
    ]
