# Generated by Django 5.1.6 on 2025-02-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20250223_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroute',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in euros', max_digits=10),
            preserve_default=False,
        ),
    ]
