# Generated by Django 5.1.6 on 2025-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_trainroute_price_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='payment_type',
            field=models.CharField(max_length=130),
        ),
    ]
